<a href="https://colab.research.google.com/github/trefftzc/cis677/blob/main/CreatingARandomMatrixWithNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating a random matrix with numpy

Numpy allows one to create a matrix with random values of whatever size we want.
The example belows creates a random matrix with 5 rows and 5 columns.

The entries are real numbers with values between 0.0 and 1.0.

In [3]:
import numpy as np

random_matrix = np.random.rand(5,5)

print(random_matrix)

[[0.64462702 0.03324329 0.93268421 0.59318664 0.91005446]
 [0.45239344 0.52241418 0.772352   0.48721681 0.30955809]
 [0.91088011 0.38931103 0.41068166 0.34163953 0.88182037]
 [0.01755934 0.44147512 0.94436955 0.39257273 0.98016688]
 [0.64968057 0.73459775 0.47502237 0.95704136 0.89322528]]


Now an example with 3 rows and 2 columns:


In [5]:
import numpy as np

random_matrix = np.random.rand(3,2)

print(random_matrix)

[[0.03773968 0.68085703]
 [0.04404673 0.84687638]
 [0.07380223 0.04359345]]


The individual entries can be accessed as in a regular list of lists in python

In [7]:
import numpy as np

random_matrix = np.random.rand(3,2)

print(random_matrix)

sum = 0.0
for i in range(3):
  for j in range(2):
    sum = sum + random_matrix[i,j]

print("The sum of all the entries is: ",sum)

[[0.2217694  0.14891324]
 [0.13447483 0.51669329]
 [0.42523632 0.18470458]]
The sum of all the entries is:  1.6317916699637427
