<a href="https://colab.research.google.com/github/trefftzc/cis677/blob/main/In_class_activity_Nov6_MIS_GPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%%writefile k4.txt
4
0 1 1 1
1 0 1 1
1 1 0 1
1 1 1 0

Writing k4.txt


In [2]:
%%writefile no_edges4.txt
4
0 0 0 0
0 0 0 0
0 0 0 0
0 0 0 0



Writing no_edges4.txt


In [3]:
%%writefile k16.txt
16
0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0

Writing k16.txt


In [4]:
%%writefile k20.txt
20
0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0

Writing k20.txt


In [5]:
%%writefile k24.txt
24
0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0

Writing k24.txt


In [6]:
%%writefile matrix_copy.py
import sys
import time
import numpy as np
from math import ceil
from numba import cuda

@cuda.jit
def device_copy_matrix(src, dst):
    x, y = cuda.grid(2)
    if x < src.shape[0] and y < src.shape[1]:
        dst[x, y] = src[x, y]



def read_adjacency_matrix(file_name):
  file_object = open(file_name, "r")
  # Input the number of rows and columns
  size = int(file_object.readline())
  rows = size
  cols = size
  # Initialize an empty matrix
  matrix = []

  # Input the matrix elements
  for i in range(rows):
    row = list(map(int, file_object.readline().split()))
    matrix.append(row)
  # Display the matrix
  # print("The matrix contained in the file ",file_name," is: ")
  # for row in matrix:
  #  print(row)
  return matrix,size




if __name__ == "__main__":

  adj_matrix,size = read_adjacency_matrix(sys.argv[1])
  adj_matrix_numpy = np.array(adj_matrix)

  arr1 = cuda.to_device(adj_matrix_numpy)
  arr2 = cuda.device_array_like(arr1)

  tpb = (size,size)
  bpg = (ceil(arr1.shape[0]/tpb[0]), ceil(arr1.shape[1]/tpb[1]))
  device_copy_matrix[bpg, tpb](arr1,arr2)

  host_arr2 = arr2.copy_to_host()

# Sanity check
  np.testing.assert_equal(adj_matrix_numpy, host_arr2)
  print(host_arr2)


Writing matrix_copy.py


In [7]:
!python matrix_copy.py k4.txt

/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]


In [12]:
%%writefile max_ind_set_numba_cuda.py
import sys
import time
import numpy as np
import numba
from math import ceil
from numba import cuda,types
from numba.cuda.cudadrv.devicearray import DeviceNDArray
import time

# A reduction on the GPU
@cuda.reduce
def max_reduce(a, b):
    if a < b:
        return b
    else:
        return a

@cuda.jit
def device_copy_matrix(src, dst):
    x, y = cuda.grid(2)
    if x < src.shape[0] and y < src.shape[1]:
        dst[x, y] = src[x, y]

@cuda.jit
def evaluateSubset(array_with_sizes:DeviceNDArray,adj_mat:DeviceNDArray,n:np.dtype=np.int64):
   this_set=cuda.local.array(32,dtype=numba.types.int64)
   value = cuda.grid(1)
   sum0s = 0
   sum1s = 0
   mask = 1
   n_elements_in_this_set = 0
   for i in range(0,n):
     if ((mask & value) != 0):
       this_set[i] = 1
       n_elements_in_this_set += 1
     else:
       this_set[i] = 0
     mask = mask * 2
   is_independent = True
   for n1 in range(n):
     for n2 in range(n):
        if (this_set[n1]==1) and (this_set[n2]==1) and (adj_mat[n1][n2] == 1):
          is_independent = False
   if (is_independent):
      array_with_sizes[value] = n_elements_in_this_set
   else:
      array_with_sizes[value] = 0



def read_adjacency_matrix(file_name):
  file_object = open(file_name, "r")
  # Input the number of rows and columns
  size = int(file_object.readline())
  rows = size
  cols = size
  # Initialize an empty matrix
  matrix = []

  # Input the matrix elements
  for i in range(rows):
    row = list(map(int, file_object.readline().split()))
    matrix.append(row)
  # Display the matrix
  # print("The matrix contained in the file ",file_name," is: ")
  # for row in matrix:
  #  print(row)
  return matrix,size




if __name__ == "__main__":
  file_name = sys.argv[1]
  adj_matrix,size = read_adjacency_matrix(file_name)
  adj_matrix_numpy = np.array(adj_matrix)

  arr1 = cuda.to_device(adj_matrix_numpy)
  adj_matrix_device = cuda.device_array_like(arr1)

  tpb = (size,size)
  bpg = (ceil(arr1.shape[0]/tpb[0]), ceil(arr1.shape[1]/tpb[1]))
  device_copy_matrix[bpg, tpb](arr1,adj_matrix_device)



  sizePowerSet = 2 ** size
  sizesGPU = cuda.device_array(sizePowerSet, dtype=np.int32)
  start_time = time.time()
  evaluateSubset.forall(sizePowerSet)( sizesGPU,adj_matrix_device,size)
  cuda.synchronize()
  end_time = time.time()
  elapsed_time = end_time - start_time
  print(file_name," = Time for evaluation including compilation: ",elapsed_time," seconds.")

  # Perform a reduction to find the maximum value
  solution = max_reduce(sizesGPU,init=0)

  start_time = time.time()
  evaluateSubset.forall(sizePowerSet)( sizesGPU,adj_matrix_device,size)
  cuda.synchronize()
  end_time = time.time()
  elapsed_time = end_time - start_time
  print(file_name," - Time for evaluation excluding compilation: ",elapsed_time," seconds.")

  # Perform a reduction on the GPU to find the maximum value
  start_time = time.time()
  solution = max_reduce(sizesGPU,init=0)
  cuda.synchronize()
  end_time = time.time()
  elapsed_time = end_time - start_time
  print(file_name," - Time for reduction on GPU: ",elapsed_time," seconds. ",sizePowerSet," elements.")
  # Consider the alternative of copying back the array with the results from the GPU
  # and performing the reduction on the CPU
  start_time = time.time()
  sizesCPU = np.zeros(sizePowerSet,dtype=np.int32)
  sizesGPU.copy_to_host(sizesCPU)
  cuda.synchronize()
  solution = np.max(sizesCPU)
  end_time = time.time()
  elapsed_time = end_time - start_time
  print(file_name," - Time for reduction on CPU (including copy): ",elapsed_time," seconds. ",sizePowerSet," elements.")
  print(file_name," - The size of a maximum independent set is: ",solution)

Overwriting max_ind_set_numba_cuda.py


In [13]:
!python max_ind_set_numba_cuda.py no_edges4.txt
!python max_ind_set_numba_cuda.py k4.txt
!python max_ind_set_numba_cuda.py k16.txt
!python max_ind_set_numba_cuda.py k20.txt
!python max_ind_set_numba_cuda.py k24.txt

/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
no_edges4.txt  = Time for evaluation including compilation:  0.1748654842376709  seconds.
no_edges4.txt  - Time for evaluation excluding compilation:  0.0005457401275634766  seconds.
no_edges4.txt  - Time for reduction on GPU:  0.0006816387176513672  seconds.  16  elements.
no_edges4.txt  - Time for reduction on CPU (including copy):  0.00019812583923339844  seconds.  16  elements.
no_edges4.txt  - The size of a maximum independent set is:  4
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU 